baseURL: https://github.com/Zardoz8901/KaraokeEternalAutomated
languageCode: en-us
title: Karaoke Hydra
permalinks:
  page: "/:slug/"
markup:
  highlight:
    style: github-dark
  goldmark:
    renderer:
      unsafe: true
disableKinds: ["taxonomy", "RSS"]
