baseURL: https://www.karaoke-eternal.com/
languageCode: en-us
title: Karaoke Eternal
permalinks:
  page: "/:slug/"
markup:
  highlight:
    style: github-dark
  goldmark:
    renderer:
      unsafe: true
disableKinds: ["taxonomy", "RSS"]
